dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hIiawvfFsvo2vQoezgE0kI7JvLWskRAkUhp0CoYdGjyQfcbNf6mF7gAh2mhaFJkXXiv7JB+m7F2UwwF6TLldNut6JJGfC9bkyzhio7Moa80on5NrxRctN3/L4CfBBGZ9durivqV16AZEpQRL788ZyykE5+tuwmOhAMnAK9XHHr8kBZH4Ad8TeZ9iyMVTt5Dlh7KnoFc/9nWRUYKr2FxINMCcmiNtKO+HzYgwwcTAdFl2V/cYDH6e+nnw7YXpe9zeUKUyyDgnt6QDqfIslwMry3HvbWoZc9OtY3aScwGIGXkZbduuqrFbu6Jey5rjuqMgj7zsfbdEoBIwFhQecfMcftpET95y8FXHBNSR+ZuODp8vJ8BSJifDz/1U6Rs82kGqXeny+0tPYmdMLRLfeANtumxu7wyWU421TMW8MWmyog4poCvcrWqN5cvXSqJTcSDM3iuob3kHS+32i2l7EMA67K386tsRwjd46gRaBQ0bVPGYpqUyVmEoplYphbD3mYH35+PH8uMbipAX6gLsZga0UOotGfMyrT7cBujpcZU6gHCRkZ1bRY6qiDFuidUuy2NgRZM6Qhd3g7ZxSCb+pIPMSNqb6DczUeZ3FFB3WkYoEO9jf8j++zunhDXRZjAqEDLRlwVHSGu+fOvhgr6RQjcmye7p3g24Xj1zB85+vm2Lww4=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
